# Generated by Django 3.2.5 on 2021-07-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
    ]
